[general]
framerate = 75
# Bars' width and space between bars in number of characters.
bars = 0
bar_width = 2
bar_spacing = 1

[color]
gradient = 1

background = '{{base16.base00.default.hex}}'

gradient_color_7 = '{{base16.base08.default.hex}}'
gradient_color_6 = '{{base16.base09.default.hex}}'
gradient_color_5 = '{{base16.base0a.default.hex}}'
gradient_color_4 = '{{base16.base0b.default.hex}}'
gradient_color_3 = '{{base16.base0c.default.hex}}'
gradient_color_2 = '{{base16.base0d.default.hex}}'
gradient_color_1 = '{{base16.base0e.default.hex}}'

[smoothing]
noise_reduction = 50
