{ pkgs, config, inputs, ... }: {
  gtk = {
    enable = true;

    cursorTheme.package = pkgs.bibata-cursors;
    cursorTheme.name = "Bibata-Modern-Classic";
    cursorTheme.size = 18;

    iconTheme.package = pkgs.candy-icons;
    iconTheme.name = "candy-icons";

    theme.name = "adw-gtk3";
    theme.package = pkgs.adw-gtk3;

    font = {
      name = "Fira Sans";
      size = 12;
    };

    gtk3.extraConfig = {
      gtk-application-prefer-dark-theme = "true ";
    };

    gtk4.extraConfig = {
      gtk-application-prefer-dark-theme = "true ";

    };
  };

  home.file.".config/gtk-3.0/gtk.css" = {
    enable = true;
    text = ''
      @define-color accent_color #${config.colorScheme.palette.base0D};
      @define-color accent_bg_color #${config.colorScheme.palette.base0D};
      @define-color accent_fg_color #${config.colorScheme.palette.base00};
      @define-color destructive_color #${config.colorScheme.palette.base08};
      @define-color destructive_bg_color #${config.colorScheme.palette.base08};
      @define-color destructive_fg_color #${config.colorScheme.palette.base00};
      @define-color success_color #${config.colorScheme.palette.base0B};
      @define-color success_bg_color #${config.colorScheme.palette.base0B};
      @define-color success_fg_color #${config.colorScheme.palette.base00};
      @define-color warning_color #${config.colorScheme.palette.base0E};
      @define-color warning_bg_color #${config.colorScheme.palette.base0E};
      @define-color warning_fg_color #${config.colorScheme.palette.base00};
      @define-color error_color #${config.colorScheme.palette.base08};
      @define-color error_bg_color #${config.colorScheme.palette.base08};
      @define-color error_fg_color #${config.colorScheme.palette.base00};
      @define-color window_bg_color #${config.colorScheme.palette.base00};
      @define-color window_fg_color #${config.colorScheme.palette.base05};
      @define-color view_bg_color #${config.colorScheme.palette.base00};
      @define-color view_fg_color #${config.colorScheme.palette.base05};
      @define-color headerbar_bg_color #${config.colorScheme.palette.base01};
      @define-color headerbar_fg_color #${config.colorScheme.palette.base05};
      # @define-color headerbar_border_color rgba({{config.colorScheme.palette.base01-dec-r}}, {{base01-dec-g}}, {{base01-dec-b}}, 0.7);
      @define-color headerbar_border_color #${config.colorScheme.palette.base01};
      @define-color headerbar_backdrop_color @window_bg_color;
      @define-color headerbar_shade_color rgba(0, 0, 0, 0.07);
      @define-color headerbar_darker_shade_color rgba(0, 0, 0, 0.07);
      @define-color sidebar_bg_color #${config.colorScheme.palette.base01};
      @define-color sidebar_fg_color #${config.colorScheme.palette.base05};
      @define-color sidebar_backdrop_color @window_bg_color;
      @define-color sidebar_shade_color rgba(0, 0, 0, 0.07);
      @define-color secondary_sidebar_bg_color @sidebar_bg_color;
      @define-color secondary_sidebar_fg_color @sidebar_fg_color;
      @define-color secondary_sidebar_backdrop_color @sidebar_backdrop_color;
      @define-color secondary_sidebar_shade_color @sidebar_shade_color;
      @define-color card_bg_color #${config.colorScheme.palette.base01};
      @define-color card_fg_color #${config.colorScheme.palette.base05};
      @define-color card_shade_color rgba(0, 0, 0, 0.07);
      @define-color dialog_bg_color #${config.colorScheme.palette.base01};
      @define-color dialog_fg_color #${config.colorScheme.palette.base05};
      @define-color popover_bg_color #${config.colorScheme.palette.base01};
      @define-color popover_fg_color #${config.colorScheme.palette.base05};
      @define-color popover_shade_color rgba(0, 0, 0, 0.07);
      @define-color shade_color rgba(0, 0, 0, 0.07);
      @define-color scrollbar_outline_color #${config.colorScheme.palette.base02};
      @define-color blue_1 #${config.colorScheme.palette.base0D};
      @define-color blue_2 #${config.colorScheme.palette.base0D};
      @define-color blue_3 #${config.colorScheme.palette.base0D};
      @define-color blue_4 #${config.colorScheme.palette.base0D};
      @define-color blue_5 #${config.colorScheme.palette.base0D};
      @define-color green_1 #${config.colorScheme.palette.base0B};
      @define-color green_2 #${config.colorScheme.palette.base0B};
      @define-color green_3 #${config.colorScheme.palette.base0B};
      @define-color green_4 #${config.colorScheme.palette.base0B};
      @define-color green_5 #${config.colorScheme.palette.base0B};
      @define-color yellow_1 #${config.colorScheme.palette.base0A};
      @define-color yellow_2 #${config.colorScheme.palette.base0A};
      @define-color yellow_3 #${config.colorScheme.palette.base0A};
      @define-color yellow_4 #${config.colorScheme.palette.base0A};
      @define-color yellow_5 #${config.colorScheme.palette.base0A};
      @define-color orange_1 #${config.colorScheme.palette.base09};
      @define-color orange_2 #${config.colorScheme.palette.base09};
      @define-color orange_3 #${config.colorScheme.palette.base09};
      @define-color orange_4 #${config.colorScheme.palette.base09};
      @define-color orange_5 #${config.colorScheme.palette.base09};
      @define-color red_1 #${config.colorScheme.palette.base08};
      @define-color red_2 #${config.colorScheme.palette.base08};
      @define-color red_3 #${config.colorScheme.palette.base08};
      @define-color red_4 #${config.colorScheme.palette.base08};
      @define-color red_5 #${config.colorScheme.palette.base08};
      @define-color purple_1 #${config.colorScheme.palette.base0E};
      @define-color purple_2 #${config.colorScheme.palette.base0E};
      @define-color purple_3 #${config.colorScheme.palette.base0E};
      @define-color purple_4 #${config.colorScheme.palette.base0E};
      @define-color purple_5 #${config.colorScheme.palette.base0E};
      @define-color brown_1 #${config.colorScheme.palette.base0F};
      @define-color brown_2 #${config.colorScheme.palette.base0F};
      @define-color brown_3 #${config.colorScheme.palette.base0F};
      @define-color brown_4 #${config.colorScheme.palette.base0F};
      @define-color brown_5 #${config.colorScheme.palette.base0F};
      @define-color light_1 #${config.colorScheme.palette.base01};
      @define-color light_2 #${config.colorScheme.palette.base01};
      @define-color light_3 #${config.colorScheme.palette.base01};
      @define-color light_4 #${config.colorScheme.palette.base01};
      @define-color light_5 #${config.colorScheme.palette.base01};
      @define-color dark_1 #${config.colorScheme.palette.base01};
      @define-color dark_2 #${config.colorScheme.palette.base01};
      @define-color dark_3 #${config.colorScheme.palette.base01};
      @define-color dark_4 #${config.colorScheme.palette.base01};
      @define-color dark_5 #${config.colorScheme.palette.base01};
    '';
  };
  xdg.configFile = {
    "gtk-4.0/gtk.css" = {
      enable = true;
      text = ''
        @define-color accent_color #${config.colorScheme.palette.base0D};
        @define-color accent_bg_color #${config.colorScheme.palette.base0D};
        @define-color accent_fg_color #${config.colorScheme.palette.base00};
        @define-color destructive_color #${config.colorScheme.palette.base08};
        @define-color destructive_bg_color #${config.colorScheme.palette.base08};
        @define-color destructive_fg_color #${config.colorScheme.palette.base00};
        @define-color success_color #${config.colorScheme.palette.base0B};
        @define-color success_bg_color #${config.colorScheme.palette.base0B};
        @define-color success_fg_color #${config.colorScheme.palette.base00};
        @define-color warning_color #${config.colorScheme.palette.base0E};
        @define-color warning_bg_color #${config.colorScheme.palette.base0E};
        @define-color warning_fg_color #${config.colorScheme.palette.base00};
        @define-color error_color #${config.colorScheme.palette.base08};
        @define-color error_bg_color #${config.colorScheme.palette.base08};
        @define-color error_fg_color #${config.colorScheme.palette.base00};
        @define-color window_bg_color #${config.colorScheme.palette.base00};
        @define-color window_fg_color #${config.colorScheme.palette.base05};
        @define-color view_bg_color #${config.colorScheme.palette.base00};
        @define-color view_fg_color #${config.colorScheme.palette.base05};
        @define-color headerbar_bg_color #${config.colorScheme.palette.base01};
        @define-color headerbar_fg_color #${config.colorScheme.palette.base05};
        # @define-color headerbar_border_color rgba({{config.colorScheme.palette.base01-dec-r}}, {{base01-dec-g}}, {{base01-dec-b}}, 0.7);
        @define-color headerbar_border_color #${config.colorScheme.palette.base01};
        @define-color headerbar_backdrop_color @window_bg_color;
        @define-color headerbar_shade_color rgba(0, 0, 0, 0.07);
        @define-color headerbar_darker_shade_color rgba(0, 0, 0, 0.07);
        @define-color sidebar_bg_color #${config.colorScheme.palette.base01};
        @define-color sidebar_fg_color #${config.colorScheme.palette.base05};
        @define-color sidebar_backdrop_color @window_bg_color;
        @define-color sidebar_shade_color rgba(0, 0, 0, 0.07);
        @define-color secondary_sidebar_bg_color @sidebar_bg_color;
        @define-color secondary_sidebar_fg_color @sidebar_fg_color;
        @define-color secondary_sidebar_backdrop_color @sidebar_backdrop_color;
        @define-color secondary_sidebar_shade_color @sidebar_shade_color;
        @define-color card_bg_color #${config.colorScheme.palette.base01};
        @define-color card_fg_color #${config.colorScheme.palette.base05};
        @define-color card_shade_color rgba(0, 0, 0, 0.07);
        @define-color dialog_bg_color #${config.colorScheme.palette.base01};
        @define-color dialog_fg_color #${config.colorScheme.palette.base05};
        @define-color popover_bg_color #${config.colorScheme.palette.base01};
        @define-color popover_fg_color #${config.colorScheme.palette.base05};
        @define-color popover_shade_color rgba(0, 0, 0, 0.07);
        @define-color shade_color rgba(0, 0, 0, 0.07);
        @define-color scrollbar_outline_color #${config.colorScheme.palette.base02};
        @define-color blue_1 #${config.colorScheme.palette.base0D};
        @define-color blue_2 #${config.colorScheme.palette.base0D};
        @define-color blue_3 #${config.colorScheme.palette.base0D};
        @define-color blue_4 #${config.colorScheme.palette.base0D};
        @define-color blue_5 #${config.colorScheme.palette.base0D};
        @define-color green_1 #${config.colorScheme.palette.base0B};
        @define-color green_2 #${config.colorScheme.palette.base0B};
        @define-color green_3 #${config.colorScheme.palette.base0B};
        @define-color green_4 #${config.colorScheme.palette.base0B};
        @define-color green_5 #${config.colorScheme.palette.base0B};
        @define-color yellow_1 #${config.colorScheme.palette.base0A};
        @define-color yellow_2 #${config.colorScheme.palette.base0A};
        @define-color yellow_3 #${config.colorScheme.palette.base0A};
        @define-color yellow_4 #${config.colorScheme.palette.base0A};
        @define-color yellow_5 #${config.colorScheme.palette.base0A};
        @define-color orange_1 #${config.colorScheme.palette.base09};
        @define-color orange_2 #${config.colorScheme.palette.base09};
        @define-color orange_3 #${config.colorScheme.palette.base09};
        @define-color orange_4 #${config.colorScheme.palette.base09};
        @define-color orange_5 #${config.colorScheme.palette.base09};
        @define-color red_1 #${config.colorScheme.palette.base08};
        @define-color red_2 #${config.colorScheme.palette.base08};
        @define-color red_3 #${config.colorScheme.palette.base08};
        @define-color red_4 #${config.colorScheme.palette.base08};
        @define-color red_5 #${config.colorScheme.palette.base08};
        @define-color purple_1 #${config.colorScheme.palette.base0E};
        @define-color purple_2 #${config.colorScheme.palette.base0E};
        @define-color purple_3 #${config.colorScheme.palette.base0E};
        @define-color purple_4 #${config.colorScheme.palette.base0E};
        @define-color purple_5 #${config.colorScheme.palette.base0E};
        @define-color brown_1 #${config.colorScheme.palette.base0F};
        @define-color brown_2 #${config.colorScheme.palette.base0F};
        @define-color brown_3 #${config.colorScheme.palette.base0F};
        @define-color brown_4 #${config.colorScheme.palette.base0F};
        @define-color brown_5 #${config.colorScheme.palette.base0F};
        @define-color light_1 #${config.colorScheme.palette.base01};
        @define-color light_2 #${config.colorScheme.palette.base01};
        @define-color light_3 #${config.colorScheme.palette.base01};
        @define-color light_4 #${config.colorScheme.palette.base01};
        @define-color light_5 #${config.colorScheme.palette.base01};
        @define-color dark_1 #${config.colorScheme.palette.base01};
        @define-color dark_2 #${config.colorScheme.palette.base01};
        @define-color dark_3 #${config.colorScheme.palette.base01};
        @define-color dark_4 #${config.colorScheme.palette.base01};
        @define-color dark_5 #${config.colorScheme.palette.base01};
      '';
    };
  };
}
